apiVersion: v1
kind: Namespace
metadata:
  name: streampulse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: streampulse
spec:
  replicas: 1
  selector: 
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
        - name: redis
          image: redis:7
          ports: [{ containerPort: 6379 }]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: streampulse
spec:
  selector: { app: redis }
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streampulse-api
  namespace: streampulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streampulse-api
  template:
    metadata:
      labels:
        app: streampulse-api
    spec:
      containers:
      - name: streampulse-api
        image: streampulse-api:local
        imagePullPolicy: IfNotPresent
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT_NUM
            value: "6379"
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: streampulse-api
  namespace: streampulse
spec:
  selector:
    app: streampulse-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streampulse-api-hpa
  namespace: streampulse
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streampulse-api
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60


        

